{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "#Only interpreter code\n",
        "# Interpreter\n",
        "INSTRUCTION_SET = [\n",
        "    \"FORWARD\",\n",
        "    \"LEFT\",\n",
        "    \"RIGHT\",\n",
        "    \"KEY\",\n",
        "    \"OPEN\",\n",
        "    \"EXIT\",\n",
        "    \"CHECKFRONT\",\n",
        "    \"CHECKKEY\",\n",
        "    \"CHECKDOOR\",\n",
        "    \"CHECKEXIT\"\n",
        "]\n",
        "\n",
        "MAX_NUM_OF_INSTRUCTIONS = 20\n",
        "\n",
        "def tokenizer(instructions):\n",
        "    tokens = []\n",
        "    for line in instructions:\n",
        "        if line not in INSTRUCTION_SET:\n",
        "            print(f\"Syntax Error: {line} is not a valid instruction.\")\n",
        "            return None\n",
        "        tokens.append(line)\n",
        "\n",
        "    if len(tokens) > MAX_NUM_OF_INSTRUCTIONS:\n",
        "        print(\"You exceeded the maximum number of instructions.\")\n",
        "        return None\n",
        "\n",
        "    return tokens\n",
        "\n",
        "def parse(tokens):\n",
        "    if tokens is None:\n",
        "        print(\"Error: No tokens to parse.\")\n",
        "        return None\n",
        "    return tokens\n",
        "\n",
        "def interpreter(parsed_instructions):\n",
        "    global robot_has_key, door_opened\n",
        "\n",
        "    for instruction in parsed_instructions:\n",
        "        print(f\"\\nInstruction: {instruction}\")\n",
        "\n",
        "        if instruction == \"FORWARD\":\n",
        "            move_forward()\n",
        "\n",
        "            if on_key():\n",
        "                pick_key()\n",
        "\n",
        "            if at_door():\n",
        "                if robot_has_key:\n",
        "                    open_door()\n",
        "                    return True\n",
        "                else:\n",
        "                    print(\"The robot is at a door but does not have the key.\")\n",
        "\n",
        "            if at_exit():\n",
        "                print(\"The robot found the exit and exits the room!\")\n",
        "                return True\n",
        "\n",
        "        elif instruction == \"LEFT\":\n",
        "            turn_left()\n",
        "\n",
        "        elif instruction == \"RIGHT\":\n",
        "            turn_right()\n",
        "\n",
        "        elif instruction == \"KEY\":\n",
        "            pick_key()\n",
        "\n",
        "        elif instruction == \"OPEN\":\n",
        "            open_door()\n",
        "\n",
        "        elif instruction == \"EXIT\":\n",
        "            if at_exit():\n",
        "                print(\"The robot exits the corridor successfully!\")\n",
        "                return True\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        elif instruction == \"CHECKFRONT\":\n",
        "            if front_is_clear():\n",
        "                print(\"Front is clear.\")\n",
        "            else:\n",
        "                print(\"Front is blocked.\")\n",
        "\n",
        "        elif instruction == \"CHECKKEY\":\n",
        "            if on_key():\n",
        "                print(\"Key detected!\")\n",
        "            else:\n",
        "                print(\"No key here.\")\n",
        "\n",
        "        elif instruction == \"CHECKDOOR\":\n",
        "            if at_door():\n",
        "                print(\"At a door.\")\n",
        "            else:\n",
        "                print(\"No door here.\")\n",
        "\n",
        "        elif instruction == \"CHECKEXIT\":\n",
        "            if at_exit():\n",
        "                print(\"At exit!\")\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        if at_exit():\n",
        "            print(\"The robot found the exit and exits the room!\")\n",
        "            return True\n",
        "\n",
        "    return False\n"
      ],
      "metadata": {
        "id": "49-HYAV2W94n"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#Only functions code\n",
        "# Functions\n",
        "def current_position():\n",
        "    row, column = robot_position\n",
        "    return map[row][column]\n",
        "\n",
        "def at_exit():\n",
        "    return current_position() == 'E'\n",
        "\n",
        "def on_key():\n",
        "    return current_position() == 'K'\n",
        "\n",
        "def at_door():\n",
        "    return current_position() == 'D'\n",
        "\n",
        "def pick_key():\n",
        "    global robot_has_key\n",
        "    if on_key():\n",
        "        robot_has_key = True\n",
        "        row, column = robot_position\n",
        "        map[row][column] = '.'  # Remove key from map\n",
        "        print(\"The robot picks up the key.\")\n",
        "    else:\n",
        "        print(\"No key to pick up.\")\n",
        "\n",
        "def open_door():\n",
        "    global door_opened\n",
        "    if at_door() and robot_has_key:\n",
        "        door_opened = True\n",
        "        row, col = robot_position\n",
        "        map[row][col] = '.'  # Door becomes passable\n",
        "        print(\"The robot opens the door! The robot exited the room!\")\n",
        "\n",
        "    else:\n",
        "        print(\"Cannot open the door (either no door or no key).\")\n",
        "\n",
        "def move_forward():\n",
        "    global robot_position\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "    if map[row][col] == '#':\n",
        "        print(\"Blocked by a wall!\")\n",
        "    else:\n",
        "        robot_position = [row, col]\n",
        "        print(f\"Robot moves forward to {robot_position}\")\n",
        "\n",
        "def turn_right():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'E', 'S', 'W']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Robot turns right, now facing {robot_direction}\")\n",
        "\n",
        "def turn_left():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'W', 'S', 'E']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Robot turns left, now facing {robot_direction}\")\n",
        "\n",
        "def front_is_clear():\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "    return map[row][col] != '#'"
      ],
      "metadata": {
        "id": "FuNEAY6nXNn6"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "LnUmR79sWqOH",
        "outputId": "e77d4bf3-f39f-4b2f-e2b4-0d2bfa14d879",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        }
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Our map is:\n",
            "##############\n",
            "#....R....D..#\n",
            "############K#\n",
            "#......E.....#\n",
            "##############\n",
            "Robot starting direction is: N\n",
            "\n",
            " Twisting corridor - example 1\n",
            "\n",
            "Instruction: CHECKFRONT\n",
            "Front is blocked.\n",
            "\n",
            "Instruction: RIGHT\n",
            "Robot turns right, now facing E\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 6]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 7]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 8]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 9]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 10]\n",
            "The robot is at a door but does not have the key.\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 11]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [1, 12]\n",
            "\n",
            "Instruction: RIGHT\n",
            "Robot turns right, now facing S\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [2, 12]\n",
            "The robot picks up the key.\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 12]\n",
            "\n",
            "Instruction: RIGHT\n",
            "Robot turns right, now facing W\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 11]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 10]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 9]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 8]\n",
            "\n",
            "Instruction: FORWARD\n",
            "Robot moves forward to [3, 7]\n",
            "The robot found the exit and exits the room!\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "'\\nmap = [list(line) for line in map3_str.strip().split(\\'\\n\\')]\\nrobot_position = [1, 4]\\nrobot_direction = random.choice(DIRECTIONS)\\nrobot_has_key = False\\ndoor_opened = False\\n\\nprint(\"Map 3:\")\\nfor row in map:\\n    print(\"\".join(row))\\nprint(f\"Robot starting direction is: {robot_direction}\")\\n\\nif robot_direction == \\'E\\':\\n    instructions3 = [\\n    \"RIGHT\",\"RIGHT\", \"FORWARD\",\"LEFT\", \"FORWARD\",\\n    \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\"EXIT\"]\\n\\nelif robot_direction == \\'W\\':\\n    instructions3=[ \"FORWARD\",\"LEFT\", \"FORWARD\",\\n    \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\"EXIT\"]\\n\\nelif robot_direction == \\'N\\':\\n    instructions3=[\"LEFT\", \"FORWARD\", \"LEFT\",\"FORWARD\",\"FORWARD\",\\n                   \"RIGHT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"RIGHT\",\\n                   \"FORWARD\",\"FORWARD\",\"LEFT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\\n\\nelse: #That means the robot is facing S initially\\n    instructions3 = [\"RIGHT\", \"FORWARD\", \"LEFT\",\"FORWARD\",\"FORWARD\",\\n                   \"RIGHT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"RIGHT\",\\n                   \"FORWARD\",\"FORWARD\",\"LEFT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\\n\\ntokens = tokenizer(instructions3)\\nparsed = parse(tokens)\\ninterpreter(parsed)\\n\\n'"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "string"
            }
          },
          "metadata": {},
          "execution_count": 1
        }
      ],
      "source": [
        "#Twisting corridor - Python - full code (including interpreter and functions)\n",
        "import random\n",
        "\n",
        "# Map - 1 example\n",
        "map_str = \"\"\"\n",
        "##############\n",
        "#....R....D..#\n",
        "############K#\n",
        "#......E.....#\n",
        "##############\n",
        "\"\"\"\n",
        "\n",
        "map = [list(line) for line in map_str.strip().split('\\n')]\n",
        "\n",
        "print(\"Our map is:\")\n",
        "for row in map:\n",
        "    print(\"\".join(row))\n",
        "\n",
        "# Global variables\n",
        "robot_position = [1, 5]  # Start at position of 'R'\n",
        "\n",
        "# Randomly choose initial direction\n",
        "DIRECTIONS = ['N', 'E', 'S', 'W']\n",
        "robot_direction=random.choice(DIRECTIONS)\n",
        "print(f\"Robot starting direction is: {robot_direction}\")\n",
        "\n",
        "robot_has_key = False\n",
        "door_opened = False\n",
        "\n",
        "\n",
        "# Functions\n",
        "def current_position():\n",
        "    row, column = robot_position\n",
        "    return map[row][column]\n",
        "\n",
        "def at_exit():\n",
        "    return current_position() == 'E'\n",
        "\n",
        "def on_key():\n",
        "    return current_position() == 'K'\n",
        "\n",
        "def at_door():\n",
        "    return current_position() == 'D'\n",
        "\n",
        "def pick_key():\n",
        "    global robot_has_key\n",
        "    if on_key():\n",
        "        robot_has_key = True\n",
        "        row, column = robot_position\n",
        "        map[row][column] = '.'  # Remove key from map\n",
        "        print(\"The robot picks up the key.\")\n",
        "    else:\n",
        "        print(\"No key to pick up.\")\n",
        "\n",
        "def open_door():\n",
        "    global door_opened\n",
        "    if at_door() and robot_has_key:\n",
        "        door_opened = True\n",
        "        row, col = robot_position\n",
        "        map[row][col] = '.'  # Door becomes passable\n",
        "        print(\"The robot opens the door! The robot exited the room!\")\n",
        "\n",
        "    else:\n",
        "        print(\"Cannot open the door (either no door or no key).\")\n",
        "\n",
        "def move_forward():\n",
        "    global robot_position\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "    if map[row][col] == '#':\n",
        "        print(\"Blocked by a wall!\")\n",
        "    else:\n",
        "        robot_position = [row, col]\n",
        "        print(f\"Robot moves forward to {robot_position}\")\n",
        "\n",
        "def turn_right():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'E', 'S', 'W']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Robot turns right, now facing {robot_direction}\")\n",
        "\n",
        "def turn_left():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'W', 'S', 'E']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Robot turns left, now facing {robot_direction}\")\n",
        "\n",
        "def front_is_clear():\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "    return map[row][col] != '#'\n",
        "\n",
        "# Interpreter\n",
        "INSTRUCTION_SET = [\n",
        "    \"FORWARD\",\n",
        "    \"LEFT\",\n",
        "    \"RIGHT\",\n",
        "    \"KEY\",\n",
        "    \"OPEN\",\n",
        "    \"EXIT\",\n",
        "    \"CHECKFRONT\",\n",
        "    \"CHECKKEY\",\n",
        "    \"CHECKDOOR\",\n",
        "    \"CHECKEXIT\"\n",
        "]\n",
        "\n",
        "MAX_NUM_OF_INSTRUCTIONS = 20\n",
        "\n",
        "def tokenizer(instructions):\n",
        "    tokens = []\n",
        "    for line in instructions:\n",
        "        if line not in INSTRUCTION_SET:\n",
        "            print(f\"Syntax Error: {line} is not a valid instruction.\")\n",
        "            return None\n",
        "        tokens.append(line)\n",
        "\n",
        "    if len(tokens) > MAX_NUM_OF_INSTRUCTIONS:\n",
        "        print(\"You exceeded the maximum number of instructions.\")\n",
        "        return None\n",
        "\n",
        "    return tokens\n",
        "\n",
        "def parse(tokens):\n",
        "    if tokens is None:\n",
        "        print(\"Error: No tokens to parse.\")\n",
        "        return None\n",
        "    return tokens\n",
        "\n",
        "def interpreter(parsed_instructions):\n",
        "    global robot_has_key, door_opened\n",
        "\n",
        "    for instruction in parsed_instructions:\n",
        "        print(f\"\\nInstruction: {instruction}\")\n",
        "\n",
        "        if instruction == \"FORWARD\":\n",
        "            move_forward()\n",
        "\n",
        "            if on_key():\n",
        "                pick_key()\n",
        "\n",
        "            if at_door():\n",
        "                if robot_has_key:\n",
        "                    open_door()\n",
        "                    return True\n",
        "                else:\n",
        "                    print(\"The robot is at a door but does not have the key.\")\n",
        "\n",
        "            if at_exit():\n",
        "                print(\"The robot found the exit and exits the room!\")\n",
        "                return True\n",
        "\n",
        "        elif instruction == \"LEFT\":\n",
        "            turn_left()\n",
        "\n",
        "        elif instruction == \"RIGHT\":\n",
        "            turn_right()\n",
        "\n",
        "        elif instruction == \"KEY\":\n",
        "            pick_key()\n",
        "\n",
        "        elif instruction == \"OPEN\":\n",
        "            open_door()\n",
        "\n",
        "        elif instruction == \"EXIT\":\n",
        "            if at_exit():\n",
        "                print(\"The robot exits the corridor successfully!\")\n",
        "                return True\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        elif instruction == \"CHECKFRONT\":\n",
        "            if front_is_clear():\n",
        "                print(\"Front is clear.\")\n",
        "            else:\n",
        "                print(\"Front is blocked.\")\n",
        "\n",
        "        elif instruction == \"CHECKKEY\":\n",
        "            if on_key():\n",
        "                print(\"Key detected!\")\n",
        "            else:\n",
        "                print(\"No key here.\")\n",
        "\n",
        "        elif instruction == \"CHECKDOOR\":\n",
        "            if at_door():\n",
        "                print(\"At a door.\")\n",
        "            else:\n",
        "                print(\"No door here.\")\n",
        "\n",
        "        elif instruction == \"CHECKEXIT\":\n",
        "            if at_exit():\n",
        "                print(\"At exit!\")\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        if at_exit():\n",
        "            print(\"The robot found the exit and exits the room!\")\n",
        "            return True\n",
        "\n",
        "    return False\n",
        "\n",
        "\n",
        "#Running - example 1\n",
        "print(\"\\n Twisting corridor - example 1\")\n",
        "if robot_direction == 'E':\n",
        "\n",
        "   instructions1 = [ \"CHECKFRONT\",\n",
        "    \"FORWARD\", \"FORWARD\",\n",
        "    \"FORWARD\",\"FORWARD\",\n",
        "    \"FORWARD\",\"FORWARD\",\n",
        "    \"FORWARD\",\"RIGHT\",\n",
        "    \"FORWARD\", \"RIGHT\", \"RIGHT\", \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\"]\n",
        "\n",
        "elif robot_direction=='W':\n",
        "        instructions1 = [ \"CHECKFRONT\",\n",
        "    \"RIGHT\", \"RIGHT\", \"FORWARD\", \"FORWARD\",\n",
        "    \"FORWARD\", \"FORWARD\", \"FORWARD\",\"FORWARD\",\"FORWARD\",\"RIGHT\", \"FORWARD\", \"RIGHT\", \"RIGHT\", \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\"\n",
        "    ]\n",
        "elif robot_direction=='N':\n",
        "        instructions1 = [ \"CHECKFRONT\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\n",
        "    \"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\", \"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\n",
        "else: #That means the direction is S\n",
        "        instructions1 = [ \"CHECKFRONT\",\n",
        "    \"LEFT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\n",
        "    \"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\", \"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\n",
        "\n",
        "tokens = tokenizer(instructions1)\n",
        "parsed = parse(tokens)\n",
        "interpreter(parsed)\n",
        "\n",
        "\n",
        "\"\"\"\n",
        "\n",
        "# Map - 2 example\n",
        "print(\"\\n Twisting corridor - example 2\")\n",
        "map2_str = \"\"\"\n",
        "########\n",
        "#R..D..#\n",
        "###.####\n",
        "#K..E..#\n",
        "########\n",
        "\"\"\"\n",
        "map = [list(line) for line in map2_str.strip().split('\\n')]\n",
        "robot_position = [1, 1]\n",
        "robot_direction = random.choice(DIRECTIONS)\n",
        "robot_has_key = False\n",
        "door_opened = False\n",
        "\n",
        "print(\"Map 2:\")\n",
        "for row in map:\n",
        "    print(\"\".join(row))\n",
        "print(f\"Robot starting direction is: {robot_direction}\")\n",
        "\n",
        "if robot_direction == 'E':\n",
        "    instructions2 = [\n",
        "    \"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\n",
        "    \"LEFT\", \"FORWARD\"]\n",
        "elif robot_direction=='W':\n",
        "    instructions2 = [\n",
        "    \"RIGHT\",\"RIGHT\",\"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\n",
        "    \"LEFT\", \"FORWARD\"]\n",
        "elif robot_direction=='N':\n",
        "    instructions2 = [\n",
        "    \"RIGHT\",\"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\"KEY\",\n",
        "    \"RIGHT\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\n",
        "    \"LEFT\", \"FORWARD\",\"FORWARD\",\"RIGHT\",\"FORWARD\",\"EXIT\"]\n",
        "\n",
        "else: #That means the robot is facing S\n",
        "    instructions2 = [\"LEFT\",\"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\n",
        "    \"RIGHT\", \"FORWARD\", \"FORWARD\",\"KEY\",\n",
        "    \"RIGHT\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\n",
        "    \"LEFT\", \"FORWARD\", \"FORWARD\", \"RIGHT\", \"FORWARD\",\"EXIT\"]\n",
        "\n",
        "tokens = tokenizer(instructions2)\n",
        "parsed = parse(tokens)\n",
        "interpreter(parsed)\n",
        "\n",
        "\n",
        "# Map Example 3\n",
        "print(\"\\n Twisting corridor - example 3\")\n",
        "map3_str = \"\"\"\n",
        "###########\n",
        "#...R..D..#\n",
        "###.#######\n",
        "#K....E...#\n",
        "###########\n",
        "\"\"\"\n",
        "map = [list(line) for line in map3_str.strip().split('\\n')]\n",
        "robot_position = [1, 4]\n",
        "robot_direction = random.choice(DIRECTIONS)\n",
        "robot_has_key = False\n",
        "door_opened = False\n",
        "\n",
        "print(\"Map 3:\")\n",
        "for row in map:\n",
        "    print(\"\".join(row))\n",
        "print(f\"Robot starting direction is: {robot_direction}\")\n",
        "\n",
        "if robot_direction == 'E':\n",
        "    instructions3 = [\n",
        "    \"RIGHT\",\"RIGHT\", \"FORWARD\",\"LEFT\", \"FORWARD\",\n",
        "    \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\"EXIT\"]\n",
        "\n",
        "elif robot_direction == 'W':\n",
        "    instructions3=[ \"FORWARD\",\"LEFT\", \"FORWARD\",\n",
        "    \"FORWARD\", \"LEFT\", \"FORWARD\", \"FORWARD\", \"FORWARD\",\"EXIT\"]\n",
        "\n",
        "elif robot_direction == 'N':\n",
        "    instructions3=[\"LEFT\", \"FORWARD\", \"LEFT\",\"FORWARD\",\"FORWARD\",\n",
        "                   \"RIGHT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"RIGHT\",\n",
        "                   \"FORWARD\",\"FORWARD\",\"LEFT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\n",
        "\n",
        "else: #That means the robot is facing S initially\n",
        "    instructions3 = [\"RIGHT\", \"FORWARD\", \"LEFT\",\"FORWARD\",\"FORWARD\",\n",
        "                   \"RIGHT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"RIGHT\",\n",
        "                   \"FORWARD\",\"FORWARD\",\"LEFT\",\"FORWARD\",\"FORWARD\",\"RIGHT\",\"FORWARD\",\"FORWARD\",\"FORWARD\",\"FORWARD\"]\n",
        "\n",
        "tokens = tokenizer(instructions3)\n",
        "parsed = parse(tokens)\n",
        "interpreter(parsed)\n",
        "\n",
        "\"\"\""
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Twisting corridor - our language code (+ python version)\n",
        "#Idea - (1) the robot turns right until it sees a clear front step;\n",
        "#       (2) then it starts going forward until it can;\n",
        "#       (3) if it cannot continue straight, the robot repeats (1) and after that (2)\n",
        "#       (4) on every step sensors check if it is the exit, if it is with a key and if the robot has the key, then checks for the door\n",
        "\n",
        "  ROBOT_HAS_KEY = NO\n",
        "    WHILE YES\n",
        "      EXIT\n",
        "\n",
        "      IF CHECKKEY\n",
        "        PICKKEY\n",
        "        ROBOT_HAS_KEY=YES\n",
        "\n",
        "      IF CHECKDOOR and ROBOT_HAS_KEY == YES\n",
        "        STOP\n",
        "\n",
        "      FOR i=0,i++,i<4\n",
        "        IF CHECKFRONT== YES\n",
        "          STOP\n",
        "        RIGHT\n",
        "\n",
        "      IF CHECKFRONT == NO\n",
        "        PRINT \"Map mistake, the robot is blocked between walls\"\n",
        "        STOP\n",
        "\n",
        "      WHILE CHECKFRONT == YES\n",
        "        FORWARD\n",
        "\n",
        "      IF EXIT == YES\n",
        "        STOP\n",
        "\n",
        "      IF CHECKKEY == YES\n",
        "        PICKKEY\n",
        "        ROBOT_HAS_KEY = YES\n",
        "\n",
        "      IF CHECKDOOR == YES and ROBOT_HAS_KEY == YES\n",
        "          STOP\n",
        "\n",
        "#Python interpretation\n",
        "\n",
        "map=[list(line) for line in map.strip().split('\\n')] #converting the map into a 2 dimensional array\n",
        "print(\"Our map is: \")\n",
        "for row in map:\n",
        "  print(row)\n",
        "\n",
        "def escape_twisting_corridor():\n",
        "  robot_has_key= False\n",
        "  while True:\n",
        "    at_exit()\n",
        "\n",
        "    if on_key():\n",
        "      pick_key()\n",
        "      robot_has_key = True\n",
        "\n",
        "    if at_door() and robot_has_key:\n",
        "      open_door()\n",
        "\n",
        "    for _ in range (4):\n",
        "      if front_is_clear():\n",
        "        break\n",
        "      turn_right()\n",
        "    if not front_is_clear():\n",
        "      print( \"Stopped: the map is not correctly presented\")\n",
        "\n",
        "\n",
        "    while front_is_clear():\n",
        "      move_forward()\n",
        "\n",
        "    if at_exit():\n",
        "      return \"Finished: the robot found the exit\"\n",
        "\n",
        "    if on_key():\n",
        "      pick_key()\n",
        "      robot_has_key = True\n",
        "\n",
        "    if at_door() and robot_has_key:\n",
        "      open_door()\n",
        "      return \"Finished: the robot found the key and open the door\""
      ],
      "metadata": {
        "id": "cBYLrzOrXj8i",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 105
        },
        "outputId": "96d8d472-76f1-47af-8d5e-f622c5f5fe1b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "error",
          "ename": "IndentationError",
          "evalue": "unexpected indent (ipython-input-3989634391.py, line 7)",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"/tmp/ipython-input-3989634391.py\"\u001b[0;36m, line \u001b[0;32m7\u001b[0m\n\u001b[0;31m    ROBOT_HAS_KEY = NO\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unexpected indent\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Insar"
      ],
      "metadata": {
        "id": "cNOO5McTiJk-"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#Room escaping - Python - full code (including interpreter and functions)\n",
        "# Case 2: Fixed Grid Room\n",
        "\n",
        "# Example maps\n",
        "map1_str = \"\"\"\n",
        "#######\n",
        "#..D..#\n",
        "#...K.#\n",
        "#.....#\n",
        "#R...E#\n",
        "#######\n",
        "\"\"\"\n",
        "\n",
        "map2_str = \"\"\"\n",
        "########\n",
        "#R.....#\n",
        "#..K.D.#\n",
        "#.....E#\n",
        "########\n",
        "\"\"\"\n",
        "\n",
        "map3_str = \"\"\"\n",
        "#########\n",
        "#.......#\n",
        "#..K....#\n",
        "#....D..#\n",
        "#.....E.#\n",
        "#R......#\n",
        "#########\n",
        "\"\"\"\n",
        "\n",
        "# Global variables\n",
        "grid = []\n",
        "robot_position = [1, 1]   # always bottom-left inside wall\n",
        "robot_direction = 'N'     # facing north\n",
        "robot_has_key = False\n",
        "door_opened = False\n",
        "\n",
        "DIRECTIONS = ['N', 'E', 'S', 'W']\n",
        "\n",
        "# Functions\n",
        "def load_map(map_str):\n",
        "    \"\"\"\n",
        "    Loads the ASCII map into `grid`.\n",
        "    Ensures the robot 'R' is at [len(grid)-2, 1] (bottom-left inside wall).\n",
        "    If not, prints error and stops.\n",
        "    \"\"\"\n",
        "    global grid, robot_position, robot_direction, robot_has_key, door_opened\n",
        "    grid = [list(line) for line in map_str.strip().split('\\n')]\n",
        "    expected_r = [len(grid) - 2, 1]\n",
        "\n",
        "    # Look for 'R'\n",
        "    found_r = None\n",
        "    for r in range(len(grid)):\n",
        "        for c in range(len(grid[0])):\n",
        "            if grid[r][c] == 'R':\n",
        "                found_r = [r, c]\n",
        "                break\n",
        "        if found_r:\n",
        "            break\n",
        "\n",
        "    if found_r != expected_r:\n",
        "        print(\"Mistake: The robot must be in the left bottom corner. Submit a proper map\")\n",
        "        return False\n",
        "\n",
        "    # Replace R with floor and set globals\n",
        "    grid[found_r[0]][found_r[1]] = '.'\n",
        "    robot_position = expected_r\n",
        "    robot_direction = 'N'\n",
        "    robot_has_key = False\n",
        "    door_opened = False\n",
        "\n",
        "    print(\"Loaded map:\")\n",
        "    for row in grid:\n",
        "        print(\"\".join(row))\n",
        "    print(f\"Starting at {robot_position}, facing {robot_direction}\\n\")\n",
        "    return True\n",
        "\n",
        "def current_position():\n",
        "    r, c = robot_position\n",
        "    return grid[r][c]\n",
        "\n",
        "def at_exit():\n",
        "    return current_position() == 'E'\n",
        "\n",
        "def on_key():\n",
        "    return current_position() == 'K'\n",
        "\n",
        "def at_door():\n",
        "    return current_position() == 'D'\n",
        "\n",
        "def pick_key():\n",
        "    global robot_has_key\n",
        "    if on_key():\n",
        "        robot_has_key = True\n",
        "        r, c = robot_position\n",
        "        grid[r][c] = '.'\n",
        "        print(\"The robot picks up the key.\")\n",
        "\n",
        "def open_door():\n",
        "    global door_opened\n",
        "    if at_door() and robot_has_key:\n",
        "        door_opened = True\n",
        "        r, c = robot_position\n",
        "        grid[r][c] = '.'\n",
        "        print(\"The robot opens the door and escapes!\")\n",
        "        return True\n",
        "    return False\n",
        "\n",
        "def move_forward():\n",
        "    global robot_position\n",
        "    r, c = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        nr, nc = r - 1, c\n",
        "    elif robot_direction == 'S':\n",
        "        nr, nc = r + 1, c\n",
        "    elif robot_direction == 'E':\n",
        "        nr, nc = r, c + 1\n",
        "    elif robot_direction == 'W':\n",
        "        nr, nc = r, c - 1\n",
        "\n",
        "    if nr < 0 or nr >= len(grid) or nc < 0 or nc >= len(grid[0]):\n",
        "        print(\"Blocked by boundary.\")\n",
        "        return\n",
        "    if grid[nr][nc] == '#':\n",
        "        print(\"Blocked by a wall!\")\n",
        "    else:\n",
        "        robot_position = [nr, nc]\n",
        "        print(f\"Robot moves forward to {robot_position}\")\n",
        "\n",
        "def turn_right():\n",
        "    global robot_direction\n",
        "    i = DIRECTIONS.index(robot_direction)\n",
        "    robot_direction = DIRECTIONS[(i + 1) % 4]\n",
        "    print(f\"Robot turns right, now facing {robot_direction}\")\n",
        "\n",
        "def turn_left():\n",
        "    global robot_direction\n",
        "    i = DIRECTIONS.index(robot_direction)\n",
        "    robot_direction = DIRECTIONS[(i - 1) % 4]\n",
        "    print(f\"Robot turns left, now facing {robot_direction}\")\n",
        "\n",
        "def front_is_clear():\n",
        "    r, c = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        r -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        r += 1\n",
        "    elif robot_direction == 'E':\n",
        "        c += 1\n",
        "    elif robot_direction == 'W':\n",
        "        c -= 1\n",
        "\n",
        "    if r < 0 or r >= len(grid) or c < 0 or c >= len(grid[0]):\n",
        "        return False\n",
        "    return grid[r][c] != '#'\n",
        "\n",
        "# Interpreter\n",
        "INSTRUCTION_SET = [\n",
        "    \"FORWARD\",\"LEFT\",\"RIGHT\",\"KEY\",\"OPEN\",\"EXIT\",\n",
        "    \"CHECKFRONT\",\"CHECKKEY\",\"CHECKDOOR\",\"CHECKEXIT\"\n",
        "]\n",
        "\n",
        "MAX_NUM_OF_INSTRUCTIONS = 20\n",
        "\n",
        "def tokenizer(instructions):\n",
        "    tokens = []\n",
        "    for line in instructions:\n",
        "        if line not in INSTRUCTION_SET:\n",
        "            print(f\"Syntax Error: {line} is not a valid instruction.\")\n",
        "            return None\n",
        "        tokens.append(line)\n",
        "    if len(tokens) > MAX_NUM_OF_INSTRUCTIONS:\n",
        "        print(\"You exceeded the maximum number of instructions.\")\n",
        "        return None\n",
        "    return tokens\n",
        "\n",
        "def parse(tokens):\n",
        "    if tokens is None:\n",
        "        print(\"Error: No tokens to parse.\")\n",
        "        return None\n",
        "    return tokens\n",
        "\n",
        "def interpreter(parsed_instructions):\n",
        "    global robot_has_key, door_opened\n",
        "\n",
        "    for instruction in parsed_instructions:\n",
        "        print(f\"\\nInstruction: {instruction}\")\n",
        "\n",
        "        if instruction == \"FORWARD\":\n",
        "            move_forward()\n",
        "            if on_key():\n",
        "                pick_key()\n",
        "            if at_door() and robot_has_key and open_door():\n",
        "                return True\n",
        "            if at_exit():\n",
        "                print(\"The robot found the exit and exits the room!\")\n",
        "                return True\n",
        "\n",
        "        elif instruction == \"LEFT\":\n",
        "            turn_left()\n",
        "\n",
        "        elif instruction == \"RIGHT\":\n",
        "            turn_right()\n",
        "\n",
        "        elif instruction == \"KEY\":\n",
        "            pick_key()\n",
        "\n",
        "        elif instruction == \"OPEN\":\n",
        "            if open_door():\n",
        "                return True\n",
        "\n",
        "        elif instruction == \"EXIT\":\n",
        "            if at_exit():\n",
        "                print(\"The robot exits the room successfully!\")\n",
        "                return True\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        elif instruction == \"CHECKFRONT\":\n",
        "            if front_is_clear():\n",
        "                print(\"Front is clear.\")\n",
        "            else:\n",
        "                print(\"Front is blocked.\")\n",
        "\n",
        "        elif instruction == \"CHECKKEY\":\n",
        "            if on_key():\n",
        "                print(\"Key detected!\")\n",
        "            else:\n",
        "                print(\"No key here.\")\n",
        "\n",
        "        elif instruction == \"CHECKDOOR\":\n",
        "            if at_door():\n",
        "                print(\"At a door.\")\n",
        "            else:\n",
        "                print(\"No door here.\")\n",
        "\n",
        "        elif instruction == \"CHECKEXIT\":\n",
        "            if at_exit():\n",
        "                print(\"At exit!\")\n",
        "            else:\n",
        "                print(\"This is not the exit.\")\n",
        "\n",
        "        if at_exit():\n",
        "            print(\"The robot found the exit and exits the room!\")\n",
        "            return True\n",
        "\n",
        "    return False\n",
        "\n",
        "# Snake-like Fixed Room Solver\n",
        "def escape_room(max_steps=200):\n",
        "    global robot_position\n",
        "    am_I_turned_right = False\n",
        "    steps = 0\n",
        "\n",
        "    while steps < max_steps:\n",
        "        while front_is_clear() and steps < max_steps:\n",
        "            move_forward()\n",
        "            if at_exit():\n",
        "                print(\"The robot found the exit and escapes!\")\n",
        "                return True\n",
        "            if on_key():\n",
        "                pick_key()\n",
        "            if at_door() and open_door():\n",
        "                return True\n",
        "            steps += 1\n",
        "\n",
        "        if am_I_turned_right:\n",
        "            turn_left()\n",
        "            if front_is_clear():\n",
        "                move_forward()\n",
        "                turn_left()\n",
        "                am_I_turned_right = False\n",
        "        else:\n",
        "            turn_right()\n",
        "            if front_is_clear():\n",
        "                move_forward()\n",
        "                turn_right()\n",
        "                am_I_turned_right = True\n",
        "        steps += 1\n",
        "\n",
        "    print(\"Stopped after max steps, no escape found.\")\n",
        "    return False\n",
        "\n",
        "# Running the examples\n",
        "print(\"\\n Running example 1\")\n",
        "if load_map(map1_str):\n",
        "    escape_room()\n",
        "\n",
        "print(\"\\n Running example 2\")\n",
        "if load_map(map2_str):\n",
        "    escape_room()\n",
        "\n",
        "print(\"\\n Running example 3\")\n",
        "if load_map(map3_str):\n",
        "    escape_room()\n"
      ],
      "metadata": {
        "id": "RG-wToQBXoJK",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "b6d086ef-1d2c-447b-a6d2-08a4e365dd18"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            " Running example 1\n",
            "Loaded map:\n",
            "#######\n",
            "#..D..#\n",
            "#...K.#\n",
            "#.....#\n",
            "#....E#\n",
            "#######\n",
            "Starting at [4, 1], facing N\n",
            "\n",
            "Robot moves forward to [3, 1]\n",
            "Robot moves forward to [2, 1]\n",
            "Robot moves forward to [1, 1]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 2]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 2]\n",
            "Robot moves forward to [3, 2]\n",
            "Robot moves forward to [4, 2]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [4, 3]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [3, 3]\n",
            "Robot moves forward to [2, 3]\n",
            "Robot moves forward to [1, 3]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 4]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 4]\n",
            "The robot picks up the key.\n",
            "Robot moves forward to [3, 4]\n",
            "Robot moves forward to [4, 4]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [4, 5]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [3, 5]\n",
            "Robot moves forward to [2, 5]\n",
            "Robot moves forward to [1, 5]\n",
            "Robot turns right, now facing E\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 5]\n",
            "Robot turns right, now facing W\n",
            "Robot moves forward to [2, 4]\n",
            "Robot moves forward to [2, 3]\n",
            "Robot moves forward to [2, 2]\n",
            "Robot moves forward to [2, 1]\n",
            "Robot turns left, now facing S\n",
            "Robot moves forward to [3, 1]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [3, 2]\n",
            "Robot moves forward to [3, 3]\n",
            "Robot moves forward to [3, 4]\n",
            "Robot moves forward to [3, 5]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [4, 5]\n",
            "Robot turns right, now facing W\n",
            "Robot moves forward to [4, 4]\n",
            "Robot moves forward to [4, 3]\n",
            "Robot moves forward to [4, 2]\n",
            "Robot moves forward to [4, 1]\n",
            "Robot turns left, now facing S\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [4, 2]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [3, 2]\n",
            "Robot moves forward to [2, 2]\n",
            "Robot moves forward to [1, 2]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 3]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 3]\n",
            "Robot moves forward to [3, 3]\n",
            "Robot moves forward to [4, 3]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [4, 4]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [3, 4]\n",
            "Robot moves forward to [2, 4]\n",
            "Robot moves forward to [1, 4]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 5]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 5]\n",
            "Robot moves forward to [3, 5]\n",
            "Robot moves forward to [4, 5]\n",
            "The robot found the exit and escapes!\n",
            "\n",
            " Running example 2\n",
            "Mistake: The robot must be in the left bottom corner. Submit a proper map\n",
            "\n",
            " Running example 3\n",
            "Loaded map:\n",
            "#########\n",
            "#.......#\n",
            "#..K....#\n",
            "#....D..#\n",
            "#.....E.#\n",
            "#.......#\n",
            "#########\n",
            "Starting at [5, 1], facing N\n",
            "\n",
            "Robot moves forward to [4, 1]\n",
            "Robot moves forward to [3, 1]\n",
            "Robot moves forward to [2, 1]\n",
            "Robot moves forward to [1, 1]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 2]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 2]\n",
            "Robot moves forward to [3, 2]\n",
            "Robot moves forward to [4, 2]\n",
            "Robot moves forward to [5, 2]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [5, 3]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [4, 3]\n",
            "Robot moves forward to [3, 3]\n",
            "Robot moves forward to [2, 3]\n",
            "The robot picks up the key.\n",
            "Robot moves forward to [1, 3]\n",
            "Robot turns right, now facing E\n",
            "Robot moves forward to [1, 4]\n",
            "Robot turns right, now facing S\n",
            "Robot moves forward to [2, 4]\n",
            "Robot moves forward to [3, 4]\n",
            "Robot moves forward to [4, 4]\n",
            "Robot moves forward to [5, 4]\n",
            "Robot turns left, now facing E\n",
            "Robot moves forward to [5, 5]\n",
            "Robot turns left, now facing N\n",
            "Robot moves forward to [4, 5]\n",
            "Robot moves forward to [3, 5]\n",
            "The robot opens the door and escapes!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "Insar"
      ],
      "metadata": {
        "id": "1hOxJDm-iN4j"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#Room escaping - our language\n",
        "# Fixed grid (room) program\n",
        "# This is program written in python for us to understand the structure\n",
        "# The idea of this program is to direct the robot using a snake type of direction\n",
        "# it goes up until it faces the wall and when it faces the wall based on the initial boolean value it either turns to the left ot tuen to the right\n",
        "# on every step sensors check if it is the exit, if it is with a key and if the robot has the key, then checks for the door\n",
        "map = \"\"\"*******\n",
        "*..D..*\n",
        "*...K.*\n",
        "*R...E*\n",
        "*******\n",
        "  \"\"\"\n",
        "map=[list(line) for line in map.strip().split('\\n')] #converting the map into a 2 dimensional array\n",
        "print(\"Our map is: \")\n",
        "for row in map:\n",
        "  print(row)\n",
        "\n",
        "def escape_the_room:\n",
        "  am_I_turned_right = False # we are using the variable am_I_turned_right to work with it as Boolean value, so that the robot know when to turn to right and when to turn to left\n",
        "\n",
        "  while True:\n",
        "    while front_is_clear:\n",
        "      move_forward()\n",
        "      if R at_exit:\n",
        "        exit()\n",
        "      if R on_key:\n",
        "        pick_key()\n",
        "      if R at_door:\n",
        "        open_door()\n",
        "\n",
        "    if am_I_turned_right:\n",
        "      turn_left()\n",
        "      if front_is_clear():\n",
        "        move_forward()\n",
        "        turn_left()\n",
        "        am_I_turned_right = False\n",
        "    else:\n",
        "      turn_right()\n",
        "      if front_is_clear():\n",
        "        move_forward()\n",
        "        turn_right()\n",
        "        am_I_turned_right = True\n",
        "\n",
        "\n",
        "\n",
        "# Fixed grid (room) program\n",
        "# This is the program written in our own language\n",
        "AM_I_TURNED_RIGHT = NO\n",
        "\n",
        "WHILE YES\n",
        "  WHILE CHECKFRONT\n",
        "    FORWARD\n",
        "    IF R CHECKEXIT\n",
        "      EXIT\n",
        "    IF R CHECKKEY\n",
        "      PICKKEY\n",
        "    IF R CHECKDOOR\n",
        "      OPEN_DOOR\n",
        "\n",
        "  IF AM_I_TURNED_RIGHT\n",
        "    LEFT\n",
        "    WHILE CHECKFRONT\n",
        "      FORWARD\n",
        "      LEFT\n",
        "      AM_I_TURNED_RIGHT = NO\n",
        "  WHILE NO\n",
        "    RIGHT\n",
        "    WHILE CHECKFRONT\n",
        "      FORWARD\n",
        "      RIGHT\n",
        "      AM_I_TURNED_RIGHT = YES\n"
      ],
      "metadata": {
        "id": "ldjGNVEkbSDF"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#(Optional task) - Room escaping with multiple keys - Python full code\n",
        "# Optional Task: Multiple keys in a rectangle room\n",
        "\n",
        "# Example maps (rectangular, walls = *, robot = R, W = winning key, K = normal key, D = door, E = exit)\n",
        "\n",
        "map1 = \"\"\"\n",
        "*******\n",
        "*..D.K*\n",
        "*...W.*\n",
        "*R.K.E*\n",
        "*******\n",
        "\"\"\"\n",
        "\n",
        "map2 = \"\"\"\n",
        "*******\n",
        "*R...K*\n",
        "*K..D.*\n",
        "*...W.E*\n",
        "*******\n",
        "\"\"\"\n",
        "\n",
        "map3 = \"\"\"\n",
        "*******\n",
        "*K..R.*\n",
        "*..D.K*\n",
        "*W..E.*\n",
        "*******\n",
        "\"\"\"\n",
        "\n",
        "# Choose which map to test\n",
        "map_data = map1\n",
        "\n",
        "# Convert map string into 2D array\n",
        "grid = [list(line) for line in map_data.strip().split('\\n')]\n",
        "print(\"Our map is:\")\n",
        "for row in grid:\n",
        "    print(\"\".join(row))\n",
        "\n",
        "# Global robot state\n",
        "robot_position = None\n",
        "robot_direction = 'N'  # Default facing north\n",
        "keys_collected = []\n",
        "door_opened = False\n",
        "\n",
        "# Find robot start\n",
        "for i, row in enumerate(grid):\n",
        "    for j, cell in enumerate(row):\n",
        "        if cell == 'R':\n",
        "            robot_position = [i, j]\n",
        "            grid[i][j] = '.'  # Clear start tile\n",
        "\n",
        "print(f\"Robot starts at {robot_position}, facing {robot_direction}\")\n",
        "\n",
        "# Functions\n",
        "\n",
        "def current_position():\n",
        "    row, col = robot_position\n",
        "    return grid[row][col]\n",
        "\n",
        "def at_exit():\n",
        "    return current_position() == 'E'\n",
        "\n",
        "def on_key():\n",
        "    return current_position() in ['K', 'W']\n",
        "\n",
        "def at_door():\n",
        "    return current_position() == 'D'\n",
        "\n",
        "def pick_key():\n",
        "    global keys_collected\n",
        "    if on_key():\n",
        "        key_here = current_position()\n",
        "        keys_collected.append(key_here)\n",
        "        row, col = robot_position\n",
        "        grid[row][col] = '.'  # Remove key from map\n",
        "        print(f\"Picked up key: {key_here}. Keys now: {keys_collected}\")\n",
        "    else:\n",
        "        print(\"No key to pick up.\")\n",
        "\n",
        "def open_door():\n",
        "    global door_opened\n",
        "    if at_door():\n",
        "        if 'W' in keys_collected:\n",
        "            door_opened = True\n",
        "            row, col = robot_position\n",
        "            grid[row][col] = '.'\n",
        "            print(\"Opened the door with the winning key! The robot exits.\")\n",
        "        else:\n",
        "            print(\"Door here, but no winning key.\")\n",
        "    else:\n",
        "        print(\"No door here.\")\n",
        "\n",
        "def move_forward():\n",
        "    global robot_position\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "\n",
        "    if grid[row][col] == '*':\n",
        "        print(\"Blocked by a wall.\")\n",
        "    else:\n",
        "        robot_position = [row, col]\n",
        "        print(f\"Moved to {robot_position}\")\n",
        "\n",
        "def turn_right():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'E', 'S', 'W']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Turned right, now facing {robot_direction}\")\n",
        "\n",
        "def turn_left():\n",
        "    global robot_direction\n",
        "    directions = ['N', 'W', 'S', 'E']\n",
        "    i = directions.index(robot_direction)\n",
        "    robot_direction = directions[(i + 1) % 4]\n",
        "    print(f\"Turned left, now facing {robot_direction}\")\n",
        "\n",
        "def front_is_clear():\n",
        "    row, col = robot_position\n",
        "    if robot_direction == 'N':\n",
        "        row -= 1\n",
        "    elif robot_direction == 'S':\n",
        "        row += 1\n",
        "    elif robot_direction == 'E':\n",
        "        col += 1\n",
        "    elif robot_direction == 'W':\n",
        "        col -= 1\n",
        "    return grid[row][col] != '*'\n",
        "\n",
        "# Algorithm\n",
        "\n",
        "def escape_room_2():\n",
        "    global keys_collected\n",
        "    am_I_turned_right = False\n",
        "\n",
        "    # Step 1: Move until wall\n",
        "    while front_is_clear():\n",
        "        move_forward()\n",
        "        if on_key():\n",
        "            pick_key()\n",
        "        if at_exit():\n",
        "            print(\"Exited through exit!\")\n",
        "            return\n",
        "\n",
        "    turn_right()\n",
        "\n",
        "    # Step 2: Move until wall (corner reached)\n",
        "    while front_is_clear():\n",
        "        move_forward()\n",
        "        if on_key():\n",
        "            pick_key()\n",
        "        if at_exit():\n",
        "            print(\"Exited through the exit!\")\n",
        "            return\n",
        "\n",
        "    # Step 3: Confirm rectangular map\n",
        "    clear_paths = 0\n",
        "    for _ in range(4):\n",
        "        turn_right()\n",
        "        if front_is_clear():\n",
        "            clear_paths += 1\n",
        "    if clear_paths != 2:\n",
        "        print(\"Map shape error: must be rectangular.\")\n",
        "        return\n",
        "\n",
        "    # Step 4: Main exploration loop\n",
        "    while True:\n",
        "        while front_is_clear():\n",
        "            move_forward()\n",
        "\n",
        "            if on_key():\n",
        "                pick_key()\n",
        "\n",
        "            if at_door():\n",
        "                if 'W' in keys_collected:\n",
        "                    open_door()\n",
        "                    return\n",
        "                else:\n",
        "                    print(\"At door but no winning key yet.\")\n",
        "\n",
        "            if at_exit():\n",
        "                print(\"Exited through the exit!\")\n",
        "                return\n",
        "\n",
        "        # Dead-end handling: right-hand rule\n",
        "        if am_I_turned_right:\n",
        "            turn_left()\n",
        "            if front_is_clear():\n",
        "                move_forward()\n",
        "                turn_left()\n",
        "                am_I_turned_right = False\n",
        "        else:\n",
        "            turn_right()\n",
        "            if front_is_clear():\n",
        "                move_forward()\n",
        "                turn_right()\n",
        "                am_I_turned_right = True\n",
        "\n",
        "# Run test\n",
        "escape_room_2()"
      ],
      "metadata": {
        "id": "FPNrXnEebfEH",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "2df5c026-a562-44b2-dc89-e6731d6ebe89"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Our map is:\n",
            "*******\n",
            "*..D.K*\n",
            "*...W.*\n",
            "*R.K.E*\n",
            "*******\n",
            "Robot starts at [3, 1], facing N\n",
            "Moved to [2, 1]\n",
            "Moved to [1, 1]\n",
            "Turned right, now facing E\n",
            "Moved to [1, 2]\n",
            "Moved to [1, 3]\n",
            "Moved to [1, 4]\n",
            "Moved to [1, 5]\n",
            "Picked up key: K. Keys now: ['K']\n",
            "Turned right, now facing S\n",
            "Turned right, now facing W\n",
            "Turned right, now facing N\n",
            "Turned right, now facing E\n",
            "Turned right, now facing S\n",
            "Moved to [2, 5]\n",
            "Turned right, now facing W\n",
            "Moved to [2, 4]\n",
            "Picked up key: W. Keys now: ['K', 'W']\n",
            "Moved to [2, 3]\n",
            "Moved to [2, 2]\n",
            "Moved to [2, 1]\n",
            "Turned left, now facing S\n",
            "Moved to [3, 1]\n",
            "Turned left, now facing E\n",
            "Moved to [3, 2]\n",
            "Moved to [3, 3]\n",
            "Picked up key: K. Keys now: ['K', 'W', 'K']\n",
            "Moved to [3, 4]\n",
            "Moved to [3, 5]\n",
            "Exited through the exit!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#(Optional task) - Room escaping with multiple keys - Our language\n",
        "KEYS = []\n",
        "AM_I_TURNED_RIGHT = NO\n",
        "\n",
        "# Step 1: Go to a corner of the room\n",
        "WHILE CHECKFRONT\n",
        "  FORWARD\n",
        "  IF CHECKKEY\n",
        "    PICKKEY\n",
        "    APPEND KEYS\n",
        "  IF CHECKEXIT\n",
        "    EXIT\n",
        "\n",
        "\n",
        "\n",
        "WHILE CHECKFRONT\n",
        "  FORWARD\n",
        "  IF CHECKKEY\n",
        "    PICKKEY\n",
        "    APPEND KEYS\n",
        "  IF CHECKEXIT\n",
        "    EXIT\n",
        "\n",
        "# Step 2: Confirm room is rectangular\n",
        "CLEAR_PATHS = 0\n",
        "FOR i=0 TO 3\n",
        "  RIGHT\n",
        "  IF CHECKFRONT\n",
        "    CLEAR_PATHS = CLEAR_PATHS + 1\n",
        "\n",
        "IF CLEAR_PATHS != 2\n",
        "  PRINT \"Map error: must be rectangular\"\n",
        "  STOP\n",
        "\n",
        "# Step 3: Exploration loop\n",
        "WHILE YES\n",
        "  WHILE CHECKFRONT\n",
        "    FORWARD\n",
        "\n",
        "    IF CHECKKEY\n",
        "      PICKKEY\n",
        "      APPEND KEYS\n",
        "\n",
        "    IF CHECKDOOR\n",
        "      IF \"W\" IN KEYS\n",
        "        OPEN\n",
        "        EXIT\n",
        "      ELSE\n",
        "        PRINT \"At door but missing winning key\"\n",
        "\n",
        "    IF CHECKEXIT\n",
        "      EXIT\n",
        "\n",
        "  # Handle walls using right-hand rule\n",
        "  IF AM_I_TURNED_RIGHT\n",
        "    LEFT\n",
        "    IF CHECKFRONT\n",
        "      FORWARD\n",
        "      LEFT\n",
        "      AM_I_TURNED_RIGHT = NO\n",
        "  ELSE\n",
        "    RIGHT\n",
        "    IF CHECKFRONT\n",
        "      FORWARD\n",
        "      RIGHT\n",
        "      AM_I_TURNED_RIGHT = YES"
      ],
      "metadata": {
        "id": "o67ZawX7eKkV"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
